name: Karos Kunst Block
favicon: null
layout_spectrum: 0.7492346996441483
typography_spectrum: 0.49321559397503734
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.779525059973821
  lightness: 0.7099739830009639
  saturation: 0.8101529399864376
  rhythmicContrast: 0.20246246573515236
purpose: []
